
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
     - GF_DATE_FORMATS_DEFAULT_TIME_FORMAT=HH:mm:ss
     - GF_AUTH_ANONYMOUS_ENABLED=true # Opsi: Untuk akses cepat tanpa login
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  mqtt-exporter:
    container_name: mqtt-exporter
    build: ./exporter
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - prometheus

  publisher:
    build: ./publisher
    container_name: mqtt-publisher

volumes:
  grafana_data: {}